import type { Metadata } from "next";
import { Tenor_Sans, Montserrat, Sen } from "next/font/google";
import Header from "./components/Header";
import GlobalShopifyCart from "./components/GlobalShopifyCart";
import { ShopifyCartProvider } from "./contexts/ShopifyCartContext";
import { CartProvider } from "./contexts/CartContext";
import "./globals.css";

const tenor = Tenor_Sans({
  weight: "400", // or whichever weight Figma shows
  subsets: ["latin"],
  variable: "--font-tenor",
});

const montserrat = Montserrat({
  weight: ["400", "700"], // add weights you use
  subsets: ["latin"],
  variable: "--font-montserrat",
});

const sen = Sen({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-sen",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${tenor.variable} ${montserrat.variable} ${sen.variable} antialiased`}
      >
        <ShopifyCartProvider>
          <CartProvider>
            <Header />
            {children}
            {/* <GlobalShopifyCart /> */}
          </CartProvider>
        </ShopifyCartProvider>
      </body>
    </html>
  );
}
